Repository NOW-SOPT-CDSP-WEB5/CGV-CLIENT, pull requests merged in 2024-05, with the labels that each got.

#9 [FEAT] home 페이지 SubMenu & 광고 섹션 퍼블리싱
  src/assets/home/images/img_home_ad1.png
  src/assets/home/images/img_home_ad2.png
  src/assets/home/images/index.ts
  src/assets/home/images/submenu/img_home_discount.png
  src/assets/home/images/submenu/img_home_mycgv.png
  src/assets/home/images/submenu/img_home_photoplay.png
  src/assets/home/images/submenu/img_home_store.png
  src/components/home/AdSection.tsx
  src/components/home/MovieChart.tsx
  src/components/home/SubMenu.tsx
  src/pages/Home.tsx
Labels: 기능 추가 ✨

#10 [FEAT] home 추천영화 퍼블리싱
  src/assets/home/icon/btn_home_videoplay.svg
  src/assets/home/icon/index.ts
  src/assets/home/images/Recommend/thumbnail1.png
  src/assets/home/images/Recommend/thumbnail2.png
  src/assets/home/images/Recommend/thumbnail3.png
  src/assets/home/images/Recommend/thumbnail4.png
  src/assets/home/images/index.ts
  src/components/home/RecommendSection.tsx
  src/components/home/RecommendVideo.tsx
  src/constants/home/recommendedMovie.ts
  src/pages/Home.tsx
  src/types/home/types.ts
Labels: 기능 추가 ✨

#11 [FEAT] home 특별관 파트 퍼블리싱
  src/assets/home/images/img_home_suitecinema.png
  src/assets/home/images/index.ts
  src/components/home/HomeSectionTitle.tsx
  src/components/home/MovieChart.tsx
  src/components/home/OverViewBtn.tsx
  src/components/home/SpecialCinema.tsx
  src/components/home/Suite/SuiteBtn.tsx
  src/components/home/Suite/SuiteMenu.tsx
  src/components/home/Suite/SuiteMenuTag.tsx
  src/pages/Home.tsx
Labels: 기능 추가 ✨

#17 [FEAT] time페이지 topBar, 영화/극장 비교 버튼 퍼블리싱
  src/assets/common/icon/ic_arrow_left.svg
  src/assets/common/icon/ic_eclipse.svg
  src/assets/common/icon/ic_putter_arrow.svg
  src/assets/common/icon/ic_putter_line.svg
  src/assets/common/icon/ic_x.svg
  src/assets/common/icon/index.ts
  src/assets/time/buttons/btn_time_addmovie.svg
  src/assets/time/buttons/btn_time_addtheater.svg
  src/assets/time/buttons/btn_time_movieinfo.svg
  src/assets/time/buttons/index.ts
  src/assets/time/icon/ic_arrow_down.svg
  src/assets/time/icon/ic_arrow_up.svg
  src/assets/time/icon/ic_movie_star.svg
  src/assets/time/icon/ic_time_change.svg
  src/assets/time/icon/ic_time_filter.svg
  src/assets/time/icon/index.ts
  src/assets/time/images/img_time_movie.svg
  src/assets/time/images/img_time_poster_mini.svg
  src/assets/time/images/img_time_semicircle.svg
  src/assets/time/images/img_time_theater.svg
  src/assets/time/images/img_timemodal_cancel.svg
  src/assets/time/images/img_timemodal_complete.svg
  src/assets/time/images/img_timemodal_seat.svg
  src/assets/time/images/index.ts
  src/components/time/AddMovieTheater.tsx
  src/components/time/AddMovieTheaterImg.tsx
  src/components/time/AddMovieTheaterWrapper.tsx
  src/components/time/TopBar.tsx
  src/components/time/dateSelect/ThisWeek.tsx
Labels: 기능 추가 ✨

#14 [FEAT] home Icecon 섹션 퍼블리싱
  src/assets/home/images/icecon/img_home_icecon.png
  src/assets/home/images/icecon/img_home_iceconbg.png
  src/assets/home/images/index.ts
  src/components/home/BookBtn.tsx
  src/components/home/IceConSection.tsx
  src/components/home/MovieChart.tsx
  src/components/home/RecommendSection.tsx
  src/components/home/movieChart/MovieContainer.tsx
  src/pages/Home.tsx
Labels: 기능 추가 ✨

#16 [FEAT] list 페이지 퍼블리싱
  src/assets/list/icons/ic_eclipse.svg
  src/assets/list/icons/ic_eclipse_MG.svg
  src/assets/list/icons/ic_home_age.png
  src/assets/list/icons/ic_list_check.svg
  src/assets/list/icons/ic_list_movietype_4DX.png
  src/assets/list/icons/ic_list_movietype_IMAX.png
  src/assets/list/icons/index.ts
  src/assets/list/images/img_list_ad.png
  src/assets/list/images/img_list_poster1.png
  src/assets/list/images/index.ts
  src/components/common/MainTopBar.tsx
  src/components/list/ListCategory.tsx
  src/components/list/ListControlBar.tsx
  src/components/list/movie/ListMovie.tsx
  src/components/list/movie/MovieDesc.tsx
  src/components/list/movie/MovieTypeTag.tsx
  src/pages/Home.tsx
  src/pages/List.tsx
Labels: 기능 추가 ✨

#12 [FEAT] movie 상단바, 영화 포스터 퍼블리싱
  src/App.tsx
  src/assets/movie/icon/btn_fab_heart_disabled.svg
  src/assets/movie/icon/btn_fab_share.svg
  src/assets/movie/icon/btn_fab_ticketing.svg
  src/assets/movie/icon/ic_arrow_left.svg
  src/assets/movie/icon/ic_movie_4dx.svg
  src/assets/movie/icon/ic_movie_egg.svg
  src/assets/movie/icon/ic_movie_goldenegg.svg
  src/assets/movie/icon/ic_movie_imax.svg
  src/assets/movie/icon/ic_movie_playing.svg
  src/assets/movie/icon/ic_movie_ticket.svg
  src/assets/movie/icon/index.ts
  src/assets/movie/images/img_movie_bg.svg
  src/components/movie/BottomBar.tsx
  src/components/movie/MovieDetail.tsx
  src/components/movie/MovieInfo.tsx
  src/components/movie/MoviePoster.tsx
  src/components/movie/TopBar.tsx
  src/pages/Movie.tsx
  src/styles/typo/number.ts
Labels: 기능 추가 ✨

#21 [FEAT] movie 예매 취소 모달 퍼블리싱
  src/components/common/modal/Modal.tsx
  src/components/movie/ModalClickPage.tsx
  src/components/movie/modal/CancelConfirmModal.tsx
  src/components/movie/modal/CancelModal.tsx
Labels: 기능 추가 ✨

#25 [FEAT] 영화 시간 선택 중앙바 퍼블리싱
  src/assets/time/images/img_time_poster_mini.svg
  src/components/time/timeList/MiddleBar.tsx
  src/components/time/timeList/TimeToggleButton.tsx
  src/components/time/timeList/TimeToggleSection.tsx
Labels: 기능 추가 ✨

#28 [FEAT] footer 퍼블리싱
  src/App.tsx
  src/components/common/Footer.tsx
Labels: 기능 추가 ✨

#24 [FEAT] 영화 상영시간 리스트 퍼블리싱
  src/assets/time/icon/ic_time_line.svg
  src/assets/time/icon/index.ts
  src/components/time/AddMovieTheater.tsx
  src/components/time/AddMovieTheaterImg.tsx
  src/components/time/AddMovieTheaterWrapper.tsx
  src/components/time/dateSelect/ThisWeek.tsx
  src/components/time/timeComparator/AddButton.tsx
  src/components/time/timeComparator/PosterWrapper.tsx
  src/components/time/timeComparator/TimeComparator.tsx
  src/components/time/timeList/EachTheatersTimeList.tsx
  src/components/time/timeList/EachTheatersTimeSection.tsx
  src/components/time/timeList/RunningTime.tsx
  src/components/time/timeList/RunningTimeSeatsWrapper.tsx
  src/components/time/timeList/Seats.tsx
  src/components/time/timeList/TimeList.tsx
  src/pages/Time.tsx
  src/utils/time/dateUtils.ts
Labels: 기능 추가 ✨

#29 [FEAT] 영화 예매 모달 퍼블리싱
  src/components/time/BookingModalPage.tsx
  src/components/time/modal/BookingConfirmModal.tsx
  src/components/time/modal/BookingModal.tsx
  src/pages/Time.tsx
Labels: 기능 추가 ✨

#27 [FEAT] movie 페이지 Info, Detail, BottomBar 퍼블리싱
  src/assets/movie/icon/btn_movie_detail.svg
  src/assets/movie/icon/ic_movie_percent.svg
  src/assets/movie/icon/ic_movie_star.svg
  src/assets/movie/icon/index.ts
  src/assets/movie/images/img_movie_heo.svg
  src/assets/movie/images/img_movie_kim.svg
  src/assets/movie/images/img_movie_lee.svg
  src/assets/movie/images/img_movie_ma.svg
  src/assets/movie/images/img_movie_park.svg
  src/assets/movie/images/img_movie_poster_1.svg
  src/assets/movie/images/img_movie_poster_2.svg
  src/assets/movie/images/img_movie_poster_3.svg
  src/assets/movie/images/img_movie_poster_4.svg
  src/assets/movie/images/img_movie_poster_5.svg
  src/assets/movie/images/index.ts
  src/components/movie/BottomBar.tsx
  src/components/movie/MovieDetail.tsx
  src/components/movie/MovieDetail/MovieDetailAudience.tsx
  src/components/movie/MovieDetail/MovieDetailBar.tsx
  src/components/movie/MovieDetail/MovieDetailCharacter.tsx
  src/components/movie/MovieDetail/MovieDetailStillcut.tsx
  src/components/movie/MovieInfo.tsx
  src/components/movie/MovieInfo/MovieInfoEgg.tsx
  src/components/movie/MovieInfo/MovieInfoSummary.tsx
  src/components/movie/MoviePoster.tsx
  src/components/movie/TopBar.tsx
  src/pages/Movie.tsx
  src/styles/typo/title.ts
Labels: 기능 추가 ✨

#47 [FEAT] 서버 요청 axios instance 생성
  .gitignore
  package.json
  src/apis/serverAxios.js
  yarn.lock
Labels: 기능 추가 ✨

#43 [FEAT] home 캐러셀
  src/components/home/Banner.tsx
Labels: 기능 추가 ✨

#53 [FEAT] home 광고목록 API 연결
  src/apis/getAds.ts
  src/apis/serverAxios.ts
  src/components/home/AdSection.tsx
  src/components/home/Banner.tsx
  src/components/home/TapBar.tsx
  src/constants/home/homeBannerData.ts
  src/types/home/types.ts
Labels: 기능 추가 ✨, home

#59 [FIX] bannerImgData undefined 경우 처리
  src/components/home/Banner.tsx
Labels: 버그 🐛, 수정 🔧

#52 [FEAT] 영화예매 시간리스트 페이지 UI 수정 & 토글 기능 추가
  src/components/time/dateSelect/ThisWeek.tsx
  src/components/time/timeList/MiddleBar.tsx
  src/components/time/timeList/TimeToggleButton.tsx
  src/components/time/timeList/TimeToggleSection.tsx
  src/pages/Time.tsx
Labels: 수정 🔧, time

#55 [FEAT] 영화 랭킹 목록 API 연결, list 페이지 적용
  package.json
  src/apis/getMovieList.ts
  src/assets/list/icons/ic_home_age_12.png
  src/assets/list/icons/ic_home_age_15.png
  src/assets/list/icons/ic_home_age_18.png
  src/assets/list/icons/ic_home_age_all.png
  src/assets/list/icons/ic_list_movietype_screenX.png
  src/assets/list/icons/index.ts
  src/components/list/ListControlBar.tsx
  src/components/list/movie/ListMovie.tsx
  src/components/list/movie/MovieTypeTag.tsx
  src/components/time/timeList/MiddleBar.tsx
  src/constants/tagType.ts
  src/pages/List.tsx
  src/types/home/types.ts
  yarn.lock
Labels: 기능 추가 ✨, list

#63 [FIX] list 페이지 map optional chaining, 더미데이터 추가
  src/constants/list/movieListDummy.ts
  src/pages/List.tsx
Labels: 수정 🔧, list

#66 [FEAT] 무비차트 API 연결
  .eslintrc.cjs
  src/assets/home/icon/ic_home_goldenegg.png
  src/assets/home/icon/index.ts
  src/components/home/HomeSectionTitle.tsx
  src/components/home/MovieChart.tsx
  src/components/home/OverViewBtn.tsx
  src/components/home/movieChart/MovieCard.tsx
  src/components/home/movieChart/MovieContainer.tsx
  src/components/list/ListControlBar.tsx
  src/components/list/movie/ListMovie.tsx
  src/pages/List.tsx
  src/styles/theme.ts
  src/utils/common/getAgeIconSrc.ts
  src/utils/home/getDDay.ts
Labels: 기능 추가 ✨, home

#73 [FEAT] list -> movie 페이지 라우팅 추가
  src/components/list/movie/ListMovie.tsx
Labels: 기능 추가 ✨, list, movie

#67 [FEAT] movieDetail API 연결
  package.json
  src/Router.tsx
  src/apis/getDetail.ts
  src/assets/movie/icon/btn_fab_heart_activate.svg
  src/assets/movie/icon/index.ts
  src/components/movie/BottomBar.tsx
  src/components/movie/MovieDetail/MovieDetailAudience.tsx
  src/components/movie/MovieInfo.tsx
  src/components/movie/MovieInfo/MovieInfoSummary.tsx
  src/components/movie/MoviePoster.tsx
  src/pages/Movie.tsx
  src/types/movie/types.ts
  yarn.lock
Labels: 기능 추가 ✨, movie

#74 [FIX] 어긋난 예매취소 모달 UI 수정
  src/components/movie/modal/CancelModal.tsx
  src/components/time/modal/BookingConfirmModal.tsx
Labels: 버그 🐛, 기능 추가 ✨, movie, time

#77 [FEAT] movie 페이지 내 좋아요 post, delete api 연결
  src/apis/DeleteHearts.ts
  src/apis/postHearts.ts
  src/components/movie/BottomBar.tsx
  src/types/movie/types.ts
Labels: 기능 추가 ✨, movie

#79 [FIX] list->movie 3번 무비로 라우팅 고정
  src/components/list/movie/ListMovie.tsx
Labels: 수정 🔧, list, movie

#80 [DOCS] README.md
  README.md
Labels: 수정 🔧

#84 [FEAT] 영화 시간 페이지 라우팅 추가
  src/components/common/Footer.tsx
  src/components/time/modal/BookingConfirmModal.tsx
  src/components/time/timeList/TimeList.tsx
  src/components/time/timeList/TimeToggleSection.tsx
  src/pages/Time.tsx
  src/styles/GlobalStyle.tsx
Labels: 기능 추가 ✨, 수정 🔧, time
